### ISSUE TITLE
Soft link to /Application folder

### ISSUE THREAD

**Issue by toooonyy** [aerobounce/homebrew-mpv-build#1]
I wonder if this's a way for this automatically soft link the the mpv.app file in the` */Cellar/mpv/version` folder to  `/Application`. 
I want this feature beacause otherwise finder won't show mpv in the open with menu after upgrading.

**Comment by aerobounce** [comment]
I guess an application bundle installed to Cellar wouldn’t show up in apps like Alfred is common problem (there's workarounds too tho) though, I've never heard of that kind of situation.
I believe that's not to with where the application is, but more likely to do with LaunchServices (`lsregister`).

If placing the app in `/Applications/` would simply solve your problem, I'd recommend using cask of mpv (mpv is also available in cask too).

**Comment by toooonyy** [comment]
Thanks for your information! with some google search i think i understand what's going on. When mpv.app is opened for the first time, it will auto associate with the media files and any new .app in the `/Application` will also be registered with Launch Services. 
So if a new mpv.app won't be recognized by system (thus double click on media files fail). But if it's opened at least once, everything is fine.
Is it possible to add somehting like ` system "open", "-a", "mpv.app"` in the `test` part?

**Comment by aerobounce** [comment]
> So if a new mpv.app in the Cellar... **(thus double click on media files fail)**.

That's surprising to hear.
If I remember correctly, I've been using this formula by myself since macOS Mojave and never experienced that. As long as an app exists on your filesystem that can handle the file you opened in Finder, it should handle it automatically (it should open that file with mpv). And that is not specific to mpv but applies to any kind of application I believe.

Unfortunately I don't think it's ideal to modify formula to resolve your problem, instead I recommend you to write a script to execute after brewing like:
```
open -a mpv
```
or to resolve your problem **fundamentally**, you may want to ask on StackOverflow (Your situation might not be specific to this mpv).

**Comment by toooonyy** [comment]
Cool, thanks. I'm using arm Mac rn so my homebrew is under `/opt`, could that make some difference?
I see a answer and will check that [link](https://stackoverflow.com/questions/435175/how-to-associate-file-type-with-macos-x-app-without-launching-it-first)

**Comment by aerobounce** [comment]
Ah, you're on M1 chip. Well, I'm not a pro so this is just a guess but system behavior might be different from Intel chip.
`/opt/` thing might be it as well, as Homebrew does not offer full support for Arm yet.
